# config file where we will put the db credentials
spring.application.name=system
#exact database address
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db
spring.datasource.username=root
spring.datasource.password=Sanjayubuntu

#spring data jpa feature below: 'update' tells the frameworks engine (hibernate) to look at the java classes and create tables of those classes
#if they dont exist. if you later add  new vars to the class(s), it will automatically execute ALTER TABLE command to add a new col
spring.jpa.hibernate.ddl-auto=update

#enables debudding output: tells the framework to print every single sql query to the terminal output
spring.jpa.show-sql=true
